### ISSUE TITLE
سوال درسی

### ISSUE THREAD

**Issue by tabatabaei100** [UIDS13991/Data-Structure#11]
نام استاد: [دکتر رمضانی] 

فصل: [ارایه و پیوندی]

سوال: [سلام ،ببخشید من توی سوال ماتریس خوش رفتار و اعداد بزرگ کد را زدم و با وجود برسی هایی که کردم کدها هنوز ایراد دارن ، اگه میشه یه کمکی کنید ممنون میشم () کدها رو آپلود کردم ]ب

**Comment by amiralikhan079** [comment]
دوست عزیز شما همون مثال صورت سوال رو به برنامتون بدین متوجه خطای کدتون میشید.
