### ISSUE TITLE
تمرین دو امتیازی

### ISSUE THREAD

**Issue by mohammad7hosein** [UIDS13991/Data-Structure#13]
نام استاد: استاد فاطمی

سری تمرین: تمرین امتیازی

تمرین: یافتن حلقه در لیست پیوندی

سوال: دیتای موجود در نود های لیست اعداد از یک تا ان هستند؟

**Comment by amiralikhan079** [comment]
نخیر دیتای موجود در لینک لیست ممکنه حتی عدد هم نباشن
