### ISSUE TITLE
array list

### ISSUE THREAD

**Issue by mohammad7hosein** [UIDS13991/Data-Structure#15]
نام استاد: فاطمی

سری تمرین: امتیازی]

تمرین: ]

سوال: امکان استفاده از اری لیست وجود داره؟ یا فقط باید از ارایه استفاده کنیم؟]

**Comment by amiralikhan079** [comment]
پاسخ باید بصورت شبه کد باشه پس آری لیست و آرایه معنی خاصی نداره ، اما اگر فکر می کنید راحت ترید استفاده کنید.
