### ISSUE TITLE
سوال ۳ تمرین امتیازی

### ISSUE THREAD

**Issue by fatemehneshat** [UIDS13991/Data-Structure#19]
نام استاد: [دکتر فاطمی]

سری تمرین: [امتیازی]

تمرین: [سوال۳]

 سوال: [سلام وقتتون بخیر.
ببخشید در سوال سوم  به سایز لینک لیست ها دسترسی داریم یا خیر؟]

**Comment by mqddd** [comment]
خیر نیازی به سایز لینک‌لیست‌ها ندارید

**Comment by ebnoheidar** [comment]
اتفاقا اگر سایز را داشته باشیم سوال راحت تر حل میشه پس نیاز داریم ولی حالا شما دسترسی بهش نمی دهید بحث دیگری است
