### ISSUE TITLE
سوال درسی

### ISSUE THREAD

**Issue by Mohammad-ali-ghasemian** [UIDS13991/Data-Structure#24]
نام استاد: [فاطمی] 

فصل: [انالیز]

سوال: سلام توی کلاس حل تمرین گفته شد این الگوریتم از مرتبه زمانی اِن هستش ، یعنی حلقه وایل ک اِن بار تکرار میشه رو حساب نکردید؟ حلقه فور داخل وایل مگه مثل دوتا حلقه فور تودرتو از مرتبه اِن ب توان دو نیستش؟
![Screenshot (28)](https://user-images.githubusercontent.com/72393114/97880009-7ca91680-1cd5-11eb-8c7d-f34db119d0b2.png)

**Comment by armanexplorer** [comment]
سلام روز شما بخیر

ببینید اون وایل ای که میگید صرفا برای اینه که کد شما چندین بار و به ازای ورودی های مختلف اجرا بشه. منظور ما از مرتبه زمانی اجرای تنها 1 بار کد اصلی بوده.

موفق باشید 🌹
