### ISSUE TITLE
رابطه پیچیده

### ISSUE THREAD

**Issue by silver380** [UIDS13991/Data-Structure#25]
نام استاد: استاد مظاهری

سری تمرین : دوم

 تمرین : رابطه پیچیده

سلام.ببخشید این سوال نباید یه پایه برای رابطه بازگشتیش داشه باشه؟
منظورم مثلا T(1)= ?

**Comment by armanexplorer** [comment]
با سلام و وقت بخیر

چون پیچیدگی زمانی را خواسته نیازی نیست بدونید مقدار پایه چیه 

همین که میدونید 
T(0)
یک مقدار مشخص داره کافیه

موفق باشید 🌹

**Comment by silver380** [comment]
ممنون
