### ISSUE TITLE
تعداد ارقام سوال اعداد بزرگ

### ISSUE THREAD

**Issue by silver380** [UIDS13991/Data-Structure#3]
نام استاد: استاد مظاهری

سری تمرین:یک

تمرین:سوال ۴ اعداد بزرگ

.سوال:سلام با توجه به اینکه  جواب خود تست کیس نمونه ۳۳ رقم هست ایا میشه تعداد خانه های داده ساختاری که در نظر میگیریم بیشتر از ۳۲ باشه یا هدف این بوده که این قضیه جور دیگه حل شه؟ممنون
@mahdimalverdi @Rad6 @mhdr-hami @armanexplorer @mqddd

**Comment by amiralikhan079** [comment]
بله میتونید بیشتر از ۳۲ خانه تعریف کنید
فقط توجه داشته باشید در صورتی که جواب یک تست کیس ۳۲ رقم شد، عدد اضافه تری چاپ نکند و فقط درصورتی که ۳۳ رقم شد ، جواب را به فرمت ۳۳ رقمی چاپ کند.
