### ISSUE TITLE
ابهام در سوال اخر تمرین سوم

### ISSUE THREAD

**Issue by silver380** [UIDS13991/Data-Structure#30]
نام استاد:مظاهری]

سری تمرین: ۳]

تمرین ۵

سلام.خسته نباشید.در سوال ۵  میشه از استک و توابع آماده زبان استفاده کنیم یا باید پیاده سازی خودمون باشه؟در متن سوال چیزی نگفتید.

**Comment by amiralikhan079** [comment]
برای سوال اخر میتونید از استک آماده استفاده کنید

**Comment by silver380** [comment]
ممنون
