### ISSUE TITLE
ماتریس متقارن

### ISSUE THREAD

**Issue by AliNazeri** [UIDS13991/Data-Structure#4]
نام استاد:رمضانی

سری تمرین: ۱  

تمرین: ۱

سوال: توی سوال اول که گذاشتید ماتریس متقارن اشتباه تعریف و معرفی شده الان با همون تعریف کد رو بنویسیم یا با تعریف صحیحش؟

**Comment by amiralikhan079** [comment]
> نام استاد:رمضانی
> 
> سری تمرین: ۱
> 
> تمرین: ۱
> 
> سوال: توی سوال اول که گذاشتید ماتریس متقارن اشتباه تعریف و معرفی شده الان با همون تعریف کد رو بنویسیم یا با تعریف صحیحش؟

**Comment by amiralikhan079** [comment]
اشتباه تعریف نشده
تعریف سوال با تعریف ماتریس ریاضی فرق داره
(همونطور که تو ریاضی ماتریس متقارن میتونه درایه منفی  داشته باشه ولی اینجا گفته نمیشه)
طبق فرض صورت سوال حل کنید

**Comment by AliNazeri** [comment]
خب الان توی چهار در چهار چطوری باید قرینه باشه

**Comment by AliNazeri** [comment]
ممنون متوجه شدم
