### ISSUE TITLE
سوال درسی

### ISSUE THREAD

**Issue by Mohammad-ali-ghasemian** [UIDS13991/Data-Structure#5]
نام استاد: فاطمی 

فصل: 1

سوال: در زبان جاوا ، چون میخوایم فقط یک مشخصه داشته باشیم از داده ها تا اونهارو ب هم وصل کنیم ، آیا میتونیم ب جای آدرس دهی از هشکد تعریفی توی خود جاوا استفاده کنیم؟ 
سوال بعدیم اینکه ، اصلا چطوری ادرس یک متغیر یا نود یا هرچیز دیگرو بدست بیاریم؟

**Comment by mqddd** [comment]
سلام. درمورد سوال اولتون از اونجایی که در جاوا دو شئ نابرابر لزوما هشکدهای متفاوتی ندارند و احتمال برخورد (برابر شدن هشکد دو شئ نابرابر) وجود داره، منطقی نیست که اینکار رو کرد. اما درمورد سوال دومتون توی زبان هایی مثل سی پلاس که مدیریت حافظه برعهده ی برنامه نویس هست امکان دسترسی به آدرس حافظه رو دارید اما توی جاوا دسترسی به آدرس شئ در حافظه رو ندارید. که البته توی جاوا این آدرس بدردتون هم نمیخوره چون جی وی ام مدیریت حافظه رو برعهده داره و حتی ممکنه آدرس یک شئ رو عوض هم بکنه.
برای آشنایی بیشتر با هشکد و آدرس حافظه این لینک ها رو ببینید:
http://eclipsesource.com/blogs/2012/09/04/the-3-things-you-should-know-about-hashcode/
https://www.baeldung.com/java-hashcode
https://stackoverflow.com/questions/1360826/how-to-get-address-of-a-java-object

**Comment by Mohammad-ali-ghasemian** [comment]
اینطور ک من دیدم کار با ادرس توی جاوا ک مستقیم نمیشه ، بصورت غیر مستقیم هم ی تیریک هایی داره اما از سطح سواد من خارجه ؛ الان مثلا توی همین مبحث لینک لیست ک نیاز ب ادرس نود ها دارم ، پیشنهاد شما از چه راهیه ؟

**Comment by mqddd** [comment]
ببینید شما اصلا نیازی به آدرس نود توی حافظه ندارین!! الان اشکالتون توی پیاده سازی کردن لینک لیست هست یا دسترسی به یک نود خاص توی لینک لیست؟؟

**Comment by Mohammad-ali-ghasemian** [comment]
من میخواستم از طریق ادرس خود متغیرها لینک لیست هارو به هم دیگه ادرس دهی کنم و به هم وصلشون کنم ، ولی مثل اینکه اینکار تو جاوا خیلی دردسر داره . پس درواقع اشکال من الان اینه ک دنبال یک راه جایگزین هستم که به هشکد رسیدم که هشکد مشکلات خودشو داره . سوال من اینه که دیگه از چه طریقی میتونم این نود های لیست رو به هم لینک کنم ؟ یعنی در واقع توی خونه ای که ادرس نود بعد توی نود فعلی دخیره شده رو چی قرار بدم؟

**Comment by mqddd** [comment]
البته احتمالا منظورتون این است که نودهارو بهم وصل کنید نه لینک لیست. چون لینک لیست شامل تعدادی نودهای متصل بهم هست. اما برای اینکه یک نود به نود دیگه متصل بشه فقط کافیه که یک متغیر از جنس نود داشته باشه (مثلا نودِ نکست) و توی کلاس لینک لیستتون مقدار نودِ نکستِ نودِ اول رو برابر با نام نودی که میخاین بهش وصل شه قرار بدین نه آدرس و یا چیز دیگه ای.
باز اگه مشکلی دارین و یا خوب متوجه نمیشین کدتون رو پیوی بفرستین تا بیشتر راهنماییتون کنم.
