### ISSUE TITLE
!!؟

### ISSUE THREAD

**Issue by ebrahim4202500** [UIDS13991/Data-Structure#6]
نام استاد: [نام استاد]
مظاهری سودانی
سری تمرین: [شماره سری تمرین]
اول
تمرین: [شماره تمرین]
اعداد بزرگ
سوال: [متن سوال]
من کدم را درست زدم ولی کویرا نمره نمیده
973613021
حسینی

**Comment by amiralikhan079** [comment]
شما در کدتون باید اون خط اول که  اسم پکیجتون رو نوشته پاک کنید تا کورا بتونه کد جاواتون رو کامپایل کنه
