### ISSUE TITLE
اعداد بزرگ

### ISSUE THREAD

**Issue by MohammaJavad** [UIDS13991/Data-Structure#7]
نام استاد:دکتر فاطمی
سری تمرین:1
تمرین:4
سوال:دررابطه با سوال4 خواستم بدونم چرا امکان ارسال کد با پایتون نیست من کلی وقت گذاشتم کد را زدم حالا می بینم ارسال نمیشه کرد درصورتی که تمربن بعدی و قبلی این مشکل را ندارد، ومن هم از هیچ کلاس آماده ای استفاده نکردم خودم پیاده سازی کردم

**Comment by amiralikhan079** [comment]
زبان پایتون برای سوال اعداد بزرگ فعال شد.
