### ISSUE TITLE
مشکل در نیو کردن ارایه _مربوط به سوال ماتریس خوش رفتار

### ISSUE THREAD

**Issue by fatemeshafiee** [UIDS13991/Data-Structure#9]
نام استاد: [نام استاد]
دکتر فاطمی
سری تمرین: [شماره سری تمرین]
1
تمرین: [شماره تمرین]
5
سوال: [متن سوال]
سلام 
وقتی این سوال رو بدون نیو کردن یسری از ارایه ها سابمیت میکردم؛ کامل میشد و بعد از سابمیت های متوالی متوجه شدم که ارایه ی 
y
رو که نیو میکنم چنین مشکلی پیش میاد و برای بقیه چنین مشکلی نیست 
 ونمیدونم چرا
زحمت میکشین بررسی کنین؟

و اینکه کلا ضرورتی به نیو کردن هست؟

پیشاپیش ممنونم

**Comment by armanexplorer** [comment]
سلام

کدهای شما را بررسی و مقایسه کردم و مشکلی توی کدهایی که خطای زمان اجرا گرفتن ندیدم
روی سیستم خودم هم بدون مشکل اجرا شد و پاسخ درست داد

یک احتمالی الان میدم ولی قطعی نیست
اونم اینکه شاید سیستمی که روی اون کد اجرا و داوری شده توان گرفتن حافظه‌ی بیشتر از هیپ را نداشته 
برای همین هم در حین اجرا، کد شما متوقف شده و سیستم خطای زمان اجرا ثبت کرده

**Comment by safdarian** [comment]
سلام
شما تو خط 40 از آخرین سابمیتتون اندازه ی بعد اول آرایه ی  وای رو
 col 
گرفتید

ولی تضمین نمیشه که اختلاف اعداد ماتریس بیشتر از 
col  
نباشه

برای همین تو خط 57 که قدر مطلق تفاضلو حساب کردین باعث بیرون زدن از آرایه میشه که خب ظاهرا به خاطر کامپایلر کوئرا وقتی آرایه رو استاتیک میگیرید موقع بیرون زدن از آرایه به یک خونه خارج از آرایه در حافظه برخورد میکنه و مقدار اونو بررسی میکنه و چون تو الگوریتمتون فقط خونه های در محدوده ی آرایه ی وای تاثیر دارن پس مشکلی پیش نیومده و اکسپت شده
ولی تو حالت داینامیک کامپایلر کوئرا اکسپشن پرت کرده برای این بیرون زدن و نتیجش شده  رانتایم ارور

درمورد ضرورت نیو کردن این نکته را بگم که زمانی که نیو می‌کنید در زمان اجرا عملیات تخصیص حافظه انجام میشه و این حافظه از حافظه‌ی هیپ گرفته میشه ولی زمانی که نیو نکنید و آرایه تعریف کنید این حافظه قبل از اجرای برنامه و از حافظه‌ی استک گرفته می‌شه و خب به همین خاطر هم یه سری محدودیت حجمی داره و از یه حدی بیشتر نمیتونید از استک حافظه بگیرید(میتونید روی سیستم خودتون با اضافه کردن صفر به عدد 10 این موضوع را امتحان کنید)

موفق باشید

**Comment by fatemeshafiee** [comment]
متوجه شدم ؛ درست شد ؛ ممنونم .
